Adding IOperationContext and OperationContext
jasonshave/CallAutomation.Extensions pull request #18
Opened 2022-11-08 21:24 UTC by Hossein-Karimy

Adding IOperationContext and OperationContext as the base interface and class for the request's OperationContext property

2022-11-09 14:09 UTC, jasonshave requested changes
Overall this looks good. I think a few tweaks could be made.

2022-11-09 14:09 UTC, jasonshave commented on src/Services/CallAutomationEventPublisher.cs
> +        string? RequestIDFrom(string operationContext) =>
I wonder if it makes sense to encapsulate this behavior into something like an `OperationContextConverter`? When we wire up the dependency injection components we could have the developer supply their own de-serialization options override to handle things like enum converters, special dictionaries, etc. etc. It would make this code more testable as well.

2022-11-09 14:09 UTC, jasonshave commented on src/Services/CallAutomationEventPublisher.cs
> +                    await _callAutomationEventHandler.Handle(callAutomationEventBase, RequestIDFrom(callAutomationEventBase.OperationContext));
I think if we extracted this method above, we could establish the operation context once and just refer to the variable.

2022-11-09 14:09 UTC, jasonshave commented on src/Services/HelperCallbackBase.cs
> +
This is probably the right place to put this code since we have no DI services on this side but my above comment about being open to having a custom serializer the developer provides would be nice. Also, so long as we're clear about the fact we're serializing their payload for them, I think this is good.

2022-11-16 17:01 UTC, Hossein-Karimy commented on src/Models/OperationContext.cs
> +        public string? RequestID { get; set; }
Yes we need to modify it internally to make sure this is matched with the callback request id

2022-11-16 17:03 UTC, Hossein-Karimy commented on src/Services/CallAutomationEventPublisher.cs
> +                    await _callAutomationEventHandler.Handle(callAutomationEventBase, RequestIDFrom(callAutomationEventBase.OperationContext));
OperationContext will be null for inbound calls

2022-11-16 17:09 UTC, Hossein-Karimy commented on src/Services/CallAutomationEventPublisher.cs
> +        string? RequestIDFrom(string operationContext) =>
because the OperationContext type/class could be different in each requests they can not provide one type for the whole publisher class and we need to let them to deserialize it based on the previous type that they serialized it

2022-11-21 20:23 UTC, jasonshave approved these changes

2023-03-30 18:59 UTC, closed without merging